import Header from "./components/Header";
import SmoothScroll from "./components/SmoothScroll";
// import Footer from "./components/Footer";
import Footer from "./components/Footer";

// Import all global styles in the root layout
// Note: Tailwind is imported last to ensure it overrides Bootstrap and other global styles
import "./styles/bootstrap.min.css";
import "./styles/style.css";
import "./styles/footer.css";
import "./styles/sociallinks.css";
import "./global.scss";
import "./styles/globals.css"; // Tailwind CSS - imported last for higher priority

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="lenis" suppressHydrationWarning>
      <body className="lenis">
        <SmoothScroll>
          <Header />
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
